// Ingredient data for HotPocketGenerator
// Each category has four bands: base, modifier, crust, seasoning
// Each item has a name, weight, and (for bases) an ingredientList

// CURRENT CHANCES
// Breakfast vegan: 0.32%
// Dinner vegan: 0.33%
// breakfast modifier: 14.7%
// breakfast crust: 12.3%
// breakfast seasoning: 10.8%
// dinner modifier: 14.4%
// dinner crust: 12.3%
// dinner seasoning: 11.8%
// dessert modifier: 14.8%
// dessert crust: 12.3%
// dessert seasoning: 11.3%
// all three breakfast reels: 0.195%
// all three dinner reels: 0.209%
// all three dessert reels: 0.206%

export type Ingredient = {
  name: string;
  weight: number;
  icon?: string; // icon name or SVG, placeholder for now
  ingredientList?: string[]; // for base only
  person?: string; // for seasoning only, fictional person who seasons
};

export type Band = Ingredient[];

export type HotPocketCategory = {
  base: Band;
  modifier: Band;
  crust: Band;
  seasoning: Band;
};

export type HotPocketData = {
  [category: string]: HotPocketCategory;
};

const hotPocketData: HotPocketData = {
  breakfast: {
    base: [
      { name: "Sausage, egg & cheese", weight: 200, ingredientList: ["pork sausage", "scrambled eggs", "cheddar cheese"] },
      { name: "Bacon, egg & cheese", weight: 200, ingredientList: ["smoked bacon", "scrambled eggs", "American cheese"] },
      { name: "Biscuits & gravy", weight: 150, ingredientList: ["country sausage", "peppered white gravy", "biscuit dough"] },
      { name: "Meat lovers hash", weight: 150, ingredientList: ["bacon", "sausage", "ham", "potatoes", "cheddar cheese"] },
      { name: "Maple sausage potato hash", weight: 120, ingredientList: ["maple-glazed sausage", "diced potatoes", "scrambled eggs"] },
      { name: "Homestead", weight: 70, ingredientList: ["ham", "cheddar", "sautéed onions", "scrambled eggs"] },
      { name: "Western sunrise scramble", weight: 120, ingredientList: ["bell peppers", "onions", "ham", "scrambled eggs", "pepper jack cheese"] },
      { name: "Chicken & waffles", weight: 100, ingredientList: ["crispy chicken", "scrambled eggs", "maple butter sauce"] },
      { name: "Chorizo breakfast taco", weight: 120, ingredientList: ["chorizo", "scrambled eggs", "cheddar cheese", "pico de gallo"] },
      { name: "Country fried steak & egg", weight: 150, ingredientList: ["country fried beef", "scrambled eggs", "white gravy"] },
      { name: "Smoked salmon", weight: 30, ingredientList: ["smoked salmon", "egg whites", "cream cheese", "chives"] },
      { name: "Canadian lumberjack", weight: 100, ingredientList: ["peameal bacon", "cheddar", "hash browns", "maple syrup glaze"] },
      { name: "Avocado toast", weight: 60, ingredientList: ["mashed avocado", "feta cheese", "diced tomatoes", "scrambled eggs"] },
      { name: "Breakfast burrito", weight: 160, ingredientList: ["sausage", "black beans", "scrambled eggs", "pepper jack cheese", "salsa verde"] },
      { name: "Southwest huevos rancheros", weight: 120, ingredientList: ["black beans", "scrambled eggs", "roasted peppers", "queso fresco", "chipotle sauce"] },
      { name: "Korean breakfast bowl", weight: 50, ingredientList: ["bulgogi beef", "kimchi", "egg", "white rice"] },
      { name: "Mediterranean morning", weight: 20, ingredientList: ["spinach", "feta cheese", "sun-dried tomato", "scrambled eggs"] },
      { name: "Everything bagel", weight: 20, ingredientList: ["egg", "ham", "cheddar cheese", "everything bagel seasoning crust"] },
      { name: "Denver omelet", weight: 50, ingredientList: ["ham", "green bell peppers", "onions", "cheddar cheese", "eggs"] },
      { name: "Sausage & sweet potato hash", weight: 20, ingredientList: ["pork sausage", "roasted sweet potatoes", "scrambled eggs"] },
      { name: "Loaded Ham & Potato Scramble", weight: 120, ingredientList: ["diced ham", "cheddar", "scrambled eggs", "hash browns"] },
      { name: "Double Bacon & Cheddar", weight: 160, ingredientList: ["crispy bacon", "cheddar", "scrambled eggs"] },
      { name: "Pork Roll & Egg Jersey Special", weight: 30, ingredientList: ["Taylor pork roll", "American cheese", "scrambled eggs"] },
      { name: "Sausage Gravy Biscuit Crunch", weight: 150, ingredientList: ["crumbled sausage", "gravy", "cheddar", "biscuit dough"] },
      { name: "Eggs Benedict Melt", weight: 90, ingredientList: ["ham", "poached-style eggs", "hollandaise-inspired sauce"] },
      { name: "Steak & Egg Western Melt", weight: 90, ingredientList: ["grilled steak", "pepper jack", "scrambled eggs", "onions"] },
      { name: "Hashbrown Breakfast Bomb", weight: 120, ingredientList: ["crispy hashbrown", "cheddar", "sausage", "scrambled eggs"] },
      { name: "Bacon Apple Maple Scramble", weight: 45, ingredientList: ["bacon", "cinnamon apples", "maple glaze", "scrambled eggs"] },
      { name: "Sriracha Sunrise", weight: 55, ingredientList: ["sausage", "scrambled eggs", "cheddar", "sriracha aioli"] },
      { name: "Fried Chicken Biscuit & Honey", weight: 50, ingredientList: ["fried chicken", "honey butter", "biscuit dough"] },
      { name: "Breakfast Chilaquiles Crunch", weight: 40, ingredientList: ["eggs", "tortilla chips", "salsa verde", "queso fresco"] },
      { name: "Spicy Huevos con Papas", weight: 45, ingredientList: ["scrambled eggs", "potato cubes", "chorizo", "hot sauce"] },
      { name: "Tamale Breakfast", weight: 30, ingredientList: ["masa dough", "shredded pork", "scrambled egg", "salsa roja"] },
      { name: "Jalapeño Sausage Scrambler", weight: 150, ingredientList: ["jalapeño sausage", "pepper jack", "scrambled eggs"] },
      { name: "Tex-Mex Tater Melt", weight: 90, ingredientList: ["tater tots", "sausage", "chipotle cheese sauce", "eggs"] },
      { name: "Truffle Egg & Spinach", weight: 20, ingredientList: ["truffle oil", "egg whites", "spinach", "goat cheese"] },
      { name: "Applewood Bacon & Leek Frittata", weight: 40, ingredientList: ["bacon", "sautéed leeks", "egg", "Swiss"] },
      { name: "Caramelized Onion & Gruyère Bake", weight: 35, ingredientList: ["scrambled eggs", "gruyère", "sweet onions", "hash base"] },
      { name: "Breakfast Caprese", weight: 30, ingredientList: ["basil", "tomato", "egg", "mozzarella"] },
      { name: "Herbed Turkey & Egg White Wrap", weight: 30, ingredientList: ["roast turkey", "egg white", "spinach", "herbs"] },
      { name: "Croque Monsieur Breakfast Melt", weight: 20, ingredientList: ["ham", "Swiss", "béchamel", "scrambled eggs"] },
      { name: "Japanese Breakfast Bowl", weight: 15, ingredientList: ["miso scrambled egg", "soy mushrooms", "scallions", "sticky rice"] },
      { name: "Mediterranean Veggie Egg", weight: 15, ingredientList: ["egg", "olives", "sun-dried tomato", "feta", "spinach"] },
      { name: "Lox & Latkes", weight: 5, ingredientList: ["smoked salmon", "grated potato", "egg", "dill cream sauce"] },
      { name: "Samosa Breakfast", weight: 5, ingredientList: ["curried potato", "peas", "scrambled eggs", "tamarind chutney"] },
      { name: "Green Chile Egg & Potato", weight: 35, ingredientList: ["roasted green chile", "scrambled eggs", "cheddar", "potatoes"] },
      { name: "Turkey Sausage Ranch Scramble", weight: 90, ingredientList: ["turkey sausage", "scrambled eggs", "ranch sauce", "cheddar"] },
      { name: "Smoked Gouda & Red Pepper Omelet", weight: 40, ingredientList: ["scrambled eggs", "roasted red peppers", "smoked gouda"] },
      { name: "Garlic Herb Mushroom & Egg", weight: 30, ingredientList: ["sautéed garlic mushrooms", "spinach", "scrambled eggs", "Swiss"] },
      { name: "Bacon Jalapeño Hash Melt", weight: 100, ingredientList: ["bacon", "jalapeños", "cheddar", "scrambled eggs", "crispy potato"] },
      { name: "Vegan Sausage, Egg & Cheese", weight: 1, ingredientList: ["vegan sausage", "Just Egg", "vegan cheddar"] },
      { name: "Vegan Bacon & Potato Hash", weight: 1, ingredientList: ["vegan bacon", "potatoes", "plant-based cheese", "tofu scramble"] },
      { name: "Vegan Chorizo & Black Bean Scramble", weight: 1, ingredientList: ["vegan chorizo", "black beans", "tofu scramble", "salsa verde"] },
      { name: "Vegan Spinach & Mushroom Melt", weight: 1, ingredientList: ["spinach", "mushrooms", "Just Egg", "vegan Swiss"] },
      { name: "Vegan Sweet Potato & Kale Frittata", weight: 1, ingredientList: ["roasted sweet potato", "kale", "tofu", "vegan cheese"] },
      { name: "Vegan Maple Tempeh & Apple", weight: 1, ingredientList: ["maple-glazed tempeh", "cinnamon apple", "Just Egg"] },
      { name: "Vegan Mediterranean Morning", weight: 1, ingredientList: ["tofu scramble", "spinach", "olives", "sun-dried tomato"] },
      { name: "Vegan Avocado & Tomato Toast", weight: 1, ingredientList: ["mashed avocado", "tofu egg", "tomato", "vegan feta"] },
      { name: "Vegan Hot Sauce Breakfast Burrito", weight: 1, ingredientList: ["vegan sausage", "black beans", "Just Egg", "hot sauce", "vegan cheddar"] },
      { name: "Vegan Everything Bagel", weight: 1, ingredientList: ["tofu egg", "vegan ham", "vegan cheddar", "everything bagel crust"] }
    ],
    modifier: [
      { name: "None", weight: 4400 },
      { name: "Cream cheese", weight: 50 },
      { name: "Chives", weight: 40 },
      { name: "Shredded cheddar", weight: 50 },
      { name: "Avocado slices", weight: 20 },
      { name: "Cilantro", weight: 20 },
      { name: "Maple syrup drizzle", weight: 20 },
      { name: "Goat cheese crumbles", weight: 30 },
      { name: "Pepper jack", weight: 40 },
      { name: "Shredded baby spinach", weight: 20 },
      { name: "Garlic aioli", weight: 10 },
      { name: "Cholula", weight: 20 },
      { name: "Tabasco", weight: 30 },
      { name: "Pickled red onion", weight: 20 },
      { name: "Crumbled breakfast sausage", weight: 40 },
      { name: "Diced bell peppers", weight: 30 },
      { name: "Hashbrown crumbles", weight: 40 },
      { name: "Yukon gold potato cubes", weight: 30 },
      { name: "Hickory ham cubes", weight: 30 },
      { name: "Sriracha", weight: 20 },
      { name: "Crispy tortilla strips", weight: 10 },
      { name: "Sharp provolone", weight: 20 },
      { name: "Fresh dill", weight: 15 },
      { name: "Green chile hash", weight: 5 },
      { name: "Spicy queso", weight: 20 },
      { name: "Crispy pancetta bits", weight: 20 },
      { name: "Applewood smoked bacon crumbles", weight: 30 },
      { name: "Charred corn", weight: 20 },
      { name: "Crumbled feta", weight: 20 },
      { name: "Toasted sesame seeds", weight: 10 },
      { name: "Crispy bacon bits", weight: 20 },
      { name: "Crispy fried shallots", weight: 20 },
    ],
    crust: [
      { name: "None", weight: 1000 },
      { name: "Croissant", weight: 30 },
      { name: "Pretzel", weight: 20 },
      { name: "Extra crispy", weight: 30 },
      { name: "Buttery biscuit", weight: 20 },
      { name: "Fried waffle", weight: 10 },
      { name: "Flakey puff pastry", weight: 20 },
      { name: "Sourdough", weight: 10 },
    ],
    seasoning: [
      { name: "None", weight: 2400 },
      { name: "Cracked black pepper", weight: 30 },
      { name: "Crushed red pepper", weight: 30 },
      { name: "Ranch", weight: 20, person: "Greg" },
      { name: "Hot honey", weight: 20, person: "Enrique" },
      { name: "Garlic onion", weight: 20 },
      { name: "Everything bagel", weight: 10 },
      { name: "Smoked paprika", weight: 10, person: "Greg" },
      { name: "Smoky maple dust", weight: 10, person: "Greg" },
      { name: "Sea salt", weight: 20, person: "An Intern" },
      { name: "Brown sugar", weight: 20 },
      { name: "Sweet chili glaze", weight: 20, person: "Enrique" },
      { name: "Herbed parmesan", weight: 10, person: "Greg" },
      { name: "Sage & thyme blend", weight: 10, person: "Greg" },
      { name: "Cinnamon", weight: 20 },
      { name: "Buttery herbs", weight: 30, person: "An Intern" },
      { name: "Habanero spice", weight: 10, person: "Enrique" },
    ],
  },
  dinner: {
    base: [
      { name: "Pepperoni pizza", weight: 200, ingredientList: ["pepperoni", "mozzarella"] },
      { name: "Meat lovers pizza", weight: 200, ingredientList: ["pepperoni", "sausage", "ham", "mozzarella"] },
      { name: "Four cheese pizza", weight: 200, ingredientList: ["mozzarella", "provolone", "parmesan", "romano"] },
      { name: "Five cheese pizza", weight: 120, ingredientList: ["mozzarella", "cheddar", "asiago", "provolone", "parmesan"] },
      { name: "Meatballs & mozzarella", weight: 150, ingredientList: ["Italian-style meatballs", "marinara sauce", "mozzarella"] },
      { name: "Philly steak & cheese", weight: 150, ingredientList: ["sliced steak", "sautéed onions", "bell peppers", "provolone"] },
      { name: "Steak & cheddar", weight: 150, ingredientList: ["grilled steak", "sharp cheddar cheese"] },
      { name: "Ham & cheese", weight: 150, ingredientList: ["honey ham", "Swiss cheese"] },
      { name: "Chicken bacon ranch", weight: 150, ingredientList: ["grilled chicken", "smoked bacon", "ranch sauce", "mozzarella"] },
      { name: "Jalapeño steak with cheese", weight: 100, ingredientList: ["spicy steak", "jalapeños", "pepper jack cheese"] },
      { name: "Cheeseburger", weight: 80, ingredientList: ["ground beef", "cheddar cheese", "ketchup-mustard sauce"] },
      { name: "Turkey, bacon & cheese", weight: 120, ingredientList: ["roasted turkey", "bacon", "American cheese"] },
      { name: "Chicken, mushroom & spinach", weight: 60, ingredientList: ["grilled chicken", "mushrooms", "spinach", "Swiss cheese"] },
      { name: "Chicken, broccoli & cheddar", weight: 120, ingredientList: ["diced chicken", "broccoli florets", "cheddar cheese"] },
      { name: "Chicken parmesan", weight: 140, ingredientList: ["breaded chicken", "marinara sauce", "mozzarella", "parmesan"] },
      { name: "BBQ beef", weight: 90, ingredientList: ["shredded beef", "barbecue sauce", "cheddar cheese"] },
      { name: "Beef Taco", weight: 120, ingredientList: ["seasoned ground beef", "cheddar cheese", "black beans"] },
      { name: "Steak Fajita", weight: 100, ingredientList: ["fajita steak strips", "grilled peppers", "onions", "Monterey Jack cheese"] },
      { name: "Italian sub", weight: 80, ingredientList: ["salami", "pepperoni", "ham", "provolone", "banana peppers"] },
      { name: "Veggie delight", weight: 10, ingredientList: ["zucchini", "bell peppers", "spinach", "mozzarella", "red onion"] },
      { name: "Spicy Buffalo Chicken Melt", weight: 90, ingredientList: ["buffalo chicken", "ranch sauce", "cheddar cheese"] },
      { name: "Pulled Pork Mac & Cheese", weight: 110, ingredientList: ["pulled pork", "macaroni", "cheddar cheese"] },
      { name: "Korean BBQ Beef", weight: 50, ingredientList: ["bulgogi beef", "kimchi", "mozzarella"] },
      { name: "Loaded Baked Potato", weight: 160, ingredientList: ["bacon", "cheddar cheese", "sour cream", "potato chunks"] },
      { name: "Nashville Hot Chicken", weight: 120, ingredientList: ["crispy hot chicken", "pickles", "creamy slaw sauce"] },
      { name: "French Dip Melt", weight: 60, ingredientList: ["roast beef", "Swiss cheese", "caramelized onions"] },
      { name: "Buffalo Ranch Veggie Wrap", weight: 20, ingredientList: ["grilled zucchini", "buffalo sauce", "ranch", "cheddar"] },
      { name: "Chipotle Chicken & Rice", weight: 70, ingredientList: ["chipotle chicken", "black beans", "rice", "Monterey Jack cheese"] },
      { name: "Pastrami Swiss Deli", weight: 45, ingredientList: ["pastrami", "Swiss cheese", "mustard aioli"] },
      { name: "Gyro-Style Pocket", weight: 25, ingredientList: ["seasoned lamb", "tzatziki sauce", "red onion", "feta"] },
      { name: "Loaded Nacho Beef", weight: 90, ingredientList: ["taco beef", "queso", "tortilla crunch"] },
      { name: "Bacon Cheeseburger Supreme", weight: 75, ingredientList: ["beef patty", "bacon", "cheddar", "burger sauce"] },
      { name: "Teriyaki Chicken & Veggies", weight: 55, ingredientList: ["teriyaki chicken", "broccoli", "carrots", "mozzarella"] },
      { name: "Spicy Italian Sausage & Peppers", weight: 100, ingredientList: ["Italian sausage", "red peppers", "provolone cheese"] },
      { name: "Spinach Artichoke Chicken", weight: 50, ingredientList: ["chicken breast", "spinach", "artichoke", "cream cheese blend"] },
      { name: "BBQ Chicken & Corn", weight: 25, ingredientList: ["BBQ chicken", "fire-roasted corn", "cheddar cheese"] },
      { name: "Reuben Melt", weight: 80, ingredientList: ["corned beef", "sauerkraut", "Swiss cheese", "thousand island"] },
      { name: "Pesto Chicken & Tomato", weight: 30, ingredientList: ["grilled chicken", "basil pesto", "mozzarella", "cherry tomato"] },
      { name: "Thai Peanut Chicken Crunch", weight: 20, ingredientList: ["peanut sauce chicken", "shredded carrots", "crispy wonton"] },
      { name: "Southwest Black Bean & Beef", weight: 45, ingredientList: ["ground beef", "black beans", "pepper jack cheese", "salsa verde"] },
      { name: "Tandoori Chicken Pocket", weight: 25, ingredientList: ["tandoori-spiced chicken", "yogurt sauce", "red onion"] },
      { name: "Vegan Spicy BBQ Jackfruit", weight: 1, ingredientList: ["BBQ jackfruit", "black beans", "grilled peppers"] },
      { name: "Cheesesteak Chimichurri", weight: 35, ingredientList: ["grilled steak", "mozzarella", "chimichurri sauce"] },
      { name: "Chicken Alfredo Melt", weight: 45, ingredientList: ["chicken", "alfredo sauce", "mozzarella", "spinach"] },
      { name: "Cheddar Brat & Sauerkraut", weight: 20, ingredientList: ["bratwurst", "cheddar", "sauerkraut"] },
      { name: "Baja Fish Taco Pocket", weight: 10, ingredientList: ["crispy fish", "cabbage slaw", "Baja sauce"] },
      { name: "Mushroom Swiss Steakhouse", weight: 30, ingredientList: ["grilled steak", "mushrooms", "Swiss cheese"] },
      { name: "Buffalo Cauliflower & Cheese", weight: 2, ingredientList: ["roasted buffalo cauliflower", "cheddar cheese", "ranch drizzle"] },
      { name: "Bacon Eggplant Parm", weight: 10, ingredientList: ["crispy eggplant", "bacon", "marinara", "mozzarella"] },
      { name: "Gouda Bacon Jam Melt", weight: 30, ingredientList: ["smoked gouda", "bacon jam", "shredded beef"] },
      { name: "Vegan Impossible Cheeseburger", weight: 1, ingredientList: ["Impossible beef", "vegan cheddar", "pickles", "burger sauce"] },
      { name: "Vegan Chipotle Black Bean Crunch", weight: 1, ingredientList: ["black beans", "corn", "vegan cheese", "tortilla crisps", "chipotle sauce"] },
      { name: "Vegan Seitan Philly Cheesesteak", weight: 1, ingredientList: ["seitan strips", "sautéed peppers and onions", "vegan provolone"] },
      { name: "Vegan Thai Peanut Tofu", weight: 1, ingredientList: ["marinated tofu", "shredded carrots", "edamame", "peanut sauce"] },
      { name: "Vegan Beyond BBQ Riblet", weight: 1, ingredientList: ["Beyond meat rib-style strips", "smoky BBQ sauce", "caramelized onions"] },
      { name: "Vegan Mediterranean Chickpea Pocket", weight: 1, ingredientList: ["spiced chickpeas", "spinach", "vegan feta", "sun-dried tomato hummus"] },
      { name: "Vegan Mushroom Stroganoff Melt", weight: 1, ingredientList: ["creamy mushroom sauce", "lentils", "caramelized onions", "vegan mozzarella"] },
      { name: "Vegan Korean BBQ Jackfruit", weight: 1, ingredientList: ["shredded BBQ jackfruit", "kimchi", "scallions", "gochujang glaze"] },
      { name: "Vegan Eggplant Parmigiana", weight: 1, ingredientList: ["breaded eggplant", "vegan mozzarella", "marinara", "basil"] },
      { name: "Vegan Sweet Potato & Black Bean Fajita", weight: 1, ingredientList: ["roasted sweet potato", "black beans", "fajita peppers", "avocado crema"] }
    ],
    modifier: [
      { name: "None", weight: 2800 },
      { name: "Caramelized onions", weight: 30 },
      { name: "Crumbled bacon", weight: 30 },
      { name: "Roasted red peppers", weight: 20 },
      { name: "Guacamole", weight: 10 },
      { name: "Shaved parmesan", weight: 20 },
      { name: "Pepperoncini rings", weight: 20 },
      { name: "Crispy onion straws", weight: 20 },
      { name: "Shredded baby spinach", weight: 10 },
      { name: "Spicy pickle chips", weight: 10 },
      { name: "Crispy tortilla strips", weight: 30 },
      { name: "Fresh basil", weight: 20 },
      { name: "Fire-roasted corn", weight: 20 },
      { name: "Roasted garlic cloves", weight: 10 },
      { name: "Sliced jalapeño", weight: 30 },
      { name: "Chopped green olives", weight: 10 },
      { name: "Crumbled blue cheese", weight: 10 },
      { name: "Pepperoni crumbles", weight: 30 },
      { name: "Corn relish", weight: 10 },
      { name: "Banana peppers", weight: 20 },
      { name: "Sweet BBQ sauce", weight: 10 },
      { name: "Artichoke hearts", weight: 10 },
      { name: "Smoky chipotle aioli", weight: 10 },
      { name: "Green chile strips", weight: 20 },
      { name: "Toasted pine nuts", weight: 10 },
      { name: "Sautéed mushrooms", weight: 20 },
    ],
    crust: [
      { name: "None", weight: 1000 },
      { name: "Croissant", weight: 30 },
      { name: "Pretzel", weight: 20 },
      { name: "Extra crispy", weight: 30 },
      { name: "Buttery biscuit", weight: 20 },
      { name: "Fried waffle", weight: 10 },
      { name: "Flakey puff pastry", weight: 20 },
      { name: "Sourdough", weight: 10 },
    ],
    seasoning: [
      { name: "None", weight: 2400 },
      { name: "Garlic butter parmesan", weight: 20, person: "Greg" },
      { name: "Italian herb", weight: 30 },
      { name: "Cracked black pepper", weight: 30 },
      { name: "Spicy taco dust", weight: 20, person: "Enrique" },
      { name: "Ranch", weight: 25, person: "Greg" },
      { name: "Extra zesty ranch", weight: 10, person: "Greg" },
      { name: "Hot honey", weight: 20, person: "Enrique" },
      { name: "Crushed red pepper", weight: 30 },
      { name: "Garlic onion", weight: 10 },
      { name: "Smoked paprika", weight: 10, person: "Greg" },
      { name: "Sweet chili glaze", weight: 10, person: "Enrique" },
      { name: "Buttery herbs", weight: 20 },
      { name: "Truffle salt & thyme", weight: 20, person: "Greg" },
      { name: "Sea salt", weight: 20, person: "An Intern" },
      { name: "Habanero spice", weight: 15, person: "Enrique" },
      { name: "Ghost pepper spice", weight: 10, person: "Enrique" },
    ],
  },
  dessert: {
    base: [
      { name: "Double fudge brownie", weight: 200, ingredientList: ["fudge brownie filling", "chocolate chips"] },
      { name: "S'mores", weight: 200, ingredientList: ["chocolate", "marshmallow cream", "graham cracker crumbles"] },
      { name: "Chocolate lava cake", weight: 150, ingredientList: ["molten chocolate center", "dark chocolate cake"] },
      { name: "Nutella & banana crumble", weight: 80, ingredientList: ["hazelnut spread", "banana slices", "oat crumble"] },
      { name: "Peanut butter cup explosion", weight: 140, ingredientList: ["peanut butter", "milk chocolate"] },
      { name: "Cookies & cream dream", weight: 100, ingredientList: ["vanilla cream", "chocolate cookie pieces"] },
      { name: "Turtle sundae", weight: 120, ingredientList: ["caramel", "pecans", "chocolate chunks"] },
      { name: "Mexican chocolate", weight: 20, ingredientList: ["spiced dark chocolate", "cinnamon"] },
      { name: "Strawberry cheesecake", weight: 60, ingredientList: ["strawberry filling", "cheesecake cream"] },
      { name: "Peach cobbler", weight: 30, ingredientList: ["spiced peach filling", "streusel topping"] },
      { name: "Apple pie", weight: 90, ingredientList: ["baked apple filling", "cinnamon sugar"] },
      { name: "Cinnamon roll delight", weight: 60, ingredientList: ["cinnamon brown sugar", "cream cheese icing"] },
      { name: "Birthday cake", weight: 80, ingredientList: ["funfetti cake batter", "vanilla frosting"] },
      { name: "Churro crunch", weight: 50, ingredientList: ["cinnamon sugar filling", "crunchy pastry bits"] },
      { name: "Boston cream", weight: 40, ingredientList: ["custard filling", "chocolate ganache"] },
      { name: "Lemon meringue", weight: 20, ingredientList: ["lemon curd", "marshmallow fluff"] },
      { name: "Tiramisu twist", weight: 30, ingredientList: ["espresso cream", "mascarpone filling"] },
      { name: "Red velvet cheesecake", weight: 60, ingredientList: ["red velvet cake", "cream cheese swirl"] },
      { name: "Gingerbread house", weight: 50, ingredientList: ["ginger-molasses filling", "vanilla icing"] },
      { name: "Cookie dough", weight: 180, ingredientList: ["chocolate chip cookie dough", "fudge swirl"] },
      { name: "Cherry pie à la mode", weight: 40, ingredientList: ["cherry compote", "vanilla cream"] },
      { name: "Salted caramel blondie", weight: 120, ingredientList: ["buttery blondie filling", "salted caramel chips"] },
      { name: "Mocha mousse", weight: 30, ingredientList: ["mocha cream", "espresso fudge"] },
      { name: "Pineapple upside-down", weight: 30, ingredientList: ["caramelized pineapple", "vanilla cake"] },
      { name: "Hazelnut tiramisu", weight: 30, ingredientList: ["hazelnut cream", "espresso sponge"] },
      { name: "Banoffee pie", weight: 5, ingredientList: ["banana slices", "caramel", "whipped cream"] },
      { name: "Espresso brownie", weight: 40, ingredientList: ["dark brownie batter", "espresso swirl"] },
      { name: "Carrot cake", weight: 30, ingredientList: ["carrot cake batter", "cream cheese filling"] },
      { name: "Baklava crunch", weight: 5, ingredientList: ["honey walnut paste", "spiced phyllo bits"] },
      { name: "Toffee apple crumble", weight: 30, ingredientList: ["cooked apples", "toffee sauce", "crumble topping"] },
      { name: "Black forest cake", weight: 30, ingredientList: ["cherry filling", "chocolate cake", "whipped cream"] },
      { name: "Pistachio cannoli", weight: 5, ingredientList: ["ricotta cream", "pistachio crumble"] },
      { name: "Biscoff cookie butter pie", weight: 30, ingredientList: ["cookie butter", "vanilla cream", "speculoos crumbles"] },
      { name: "Orange creamsicle", weight: 10, ingredientList: ["orange gel", "sweet cream"] },
      { name: "Almond joyride", weight: 20, ingredientList: ["almond pieces", "cookie butter swirl"] },
      { name: "Maple pecan pie", weight: 100, ingredientList: ["maple glaze", "candied pecans"] },
      { name: "Key lime blast", weight: 10, ingredientList: ["key lime curd", "graham crust bits"] },
      { name: "Chocolate malt shake", weight: 30, ingredientList: ["malted chocolate cream", "vanilla swirl"] },
      { name: "Berry cobbler", weight: 10, ingredientList: ["mixed berry filling", "streusel bits"] },
      { name: "Crème brûlée", weight: 20, ingredientList: ["vanilla custard", "caramelized sugar shell"] },
      { name: "Chocolate cherry cordials", weight: 20, ingredientList: ["cherry compote", "chocolate ganache"] },
      { name: "French silk", weight: 30, ingredientList: ["silky chocolate mousse", "whipped topping"] },
      { name: "Snickerdoodle swirl", weight: 100, ingredientList: ["cinnamon sugar dough", "vanilla icing"] },
      { name: "Raspberry white chocolate", weight: 30, ingredientList: ["raspberry jam", "white chocolate chips"] },
      { name: "Holiday Edition: Eggnog Custard Delight", weight: 5, ingredientList: ["eggnog custard", "nutmeg", "vanilla glaze"] },
      { name: "Holiday Edition: Peppermint Bark Crunch", weight: 5, ingredientList: ["white chocolate", "peppermint pieces", "dark chocolate chips"] },
      { name: "Holiday Edition: Spiced Cranberry Compote", weight: 5, ingredientList: ["cranberry compote", "orange zest", "cinnamon crumble"] },
      { name: "Holiday Edition: Gingerbread Latte Cream", weight: 5, ingredientList: ["gingerbread spice cream", "coffee-infused icing", "molasses swirl"] },
      { name: "Holiday Edition: Hot Cocoa & Marshmallow", weight: 5, ingredientList: ["rich cocoa filling", "mini marshmallows", "chocolate chips"] },
      { name: "Holiday Edition: Sugar Cookie Meltaway", weight: 5, ingredientList: ["vanilla sugar cookie dough", "buttery icing", "holiday sprinkles"] },
      { name: "Holiday Edition: Sticky Toffee Fig Pudding", weight: 5, ingredientList: ["toffee sauce", "diced figs", "spiced cake batter"] },
      { name: "Holiday Edition: White Chocolate Snickerdoodle", weight: 5, ingredientList: ["white chocolate chunks", "cinnamon-sugar dough", "vanilla glaze"] },
      { name: "Holiday Edition: Holiday Fruitcake Remix", weight: 5, ingredientList: ["spiced cake", "candied cherries", "pecans", "rum glaze"] },
      { name: "Holiday Edition: Chocolate Chestnut Cream", weight: 5, ingredientList: ["chestnut purée", "chocolate ganache", "whipped cream center"] }
    ],
    modifier: [
      { name: "None", weight: 3600 },
      { name: "Whipped cream", weight: 20 },
      { name: "Cream cheese", weight: 30 },
      { name: "Marshmallow fluff", weight: 30 }, 
      { name: "Salted caramel sauce", weight: 20 },
      { name: "Peanut butter swizzle", weight: 30 },
      { name: "Hot fudge", weight: 40 },
      { name: "Custard", weight: 20 },
      { name: "Espresso whipped cream", weight: 20 },
      { name: "Chocolate chips", weight: 40 },
      { name: "Toffee bits", weight: 30 },
      { name: "Gingersnap crumbles", weight: 20 },
      { name: "Chopped pecans", weight: 30 },
      { name: "Nutella swirl", weight: 30 },
      { name: "Pistachio crumbles", weight: 10 },
      { name: "Macadamia nuts", weight: 10 },
      { name: "Cheesecake", weight: 10 },
      { name: "Cookie butter", weight: 20 },
      { name: "Streusel crumble", weight: 20 },
      { name: "Sliced bananas", weight: 10 },
      { name: "Fresh strawberries", weight: 10 },
      { name: "White chocolate drizzle", weight: 30 },
      { name: "Crushed Oreos", weight: 40 },
      { name: "Mini marshmallows", weight: 30 },
      { name: "Almond slivers", weight: 20 },
      { name: "Chocolate wafers", weight: 10 },
      { name: "Maple syrup swizzle", weight: 20 },
      { name: "Mocha crumble", weight: 10 },
      { name: "Biscoff cookie crumble", weight: 20 },
      { name: "Cereal crunch topping", weight: 10 },
      { name: "Hazelnut crumbs", weight: 15 },
      { name: "Brownie crumbles", weight: 20 },
    ],
    crust: [
      { name: "None", weight: 1000 },
      { name: "Croissant", weight: 30 },
      { name: "Pretzel", weight: 20 },
      { name: "Extra crispy", weight: 30 },
      { name: "Buttery biscuit", weight: 20 },
      { name: "Fried waffle", weight: 10 },
      { name: "Flakey puff pastry", weight: 20 },
      { name: "Sourdough", weight: 10 },
    ],
    seasoning: [
      { name: "None", weight: 2200 },
      { name: "Cinnamon sugar dust", weight: 20 },
      { name: "Powdered sugar glaze", weight: 20, person: "Greg" },
      { name: "Salted Caramel sugar", weight: 20 },
      { name: "Brown sugar dust", weight: 20 },
      { name: "Biscoff cookie crumble", weight: 10 },
      { name: "Marshmallow glaze", weight: 10, person: "Greg" },
      { name: "Maple sugar glaze", weight: 20, person: "Greg" },
      { name: "Honey butter glaze", weight: 10, person: "Greg" },
      { name: "Sprinkles", weight: 10, person: "An Intern" },
      { name: "Chocolate sprinkles", weight: 20, person: "An Intern" },
      { name: "Oreo crumble dust", weight: 30 },
      { name: "Cocoa sugar", weight: 30 },
      { name: "Espresso sugar dust", weight: 10, person: "Greg" },
      { name: "Cinnamon chili cocoa dust", weight: 10, person: "Enrique" },
      { name: "Lemon zest sugar", weight: 10 },
      { name: "Glazed donut", weight: 10, person: "Greg" },
    ],
  },
};

export default hotPocketData; 