// Ingredient data for HotPocketGenerator
// Each category has four bands: base, modifier, crust, seasoning
// Each item has a name, weight, and (for bases) an ingredientList

export type Ingredient = {
  name: string;
  weight: number;
  icon?: string; // icon name or SVG, placeholder for now
  ingredientList?: string[]; // for base only
};

export type Band = Ingredient[];

export type HotPocketCategory = {
  base: Band;
  modifier: Band;
  crust: Band;
  seasoning: Band;
};

export type HotPocketData = {
  [category: string]: HotPocketCategory;
};

const hotPocketData: HotPocketData = {
  breakfast: {
    base: [
      { name: "Sausage, egg & cheese", weight: 100, ingredientList: ["pork sausage", "scrambled eggs", "cheddar cheese"] },
      { name: "Bacon, egg & cheese", weight: 100, ingredientList: ["smoked bacon", "scrambled eggs", "American cheese"] },
      { name: "Biscuits & gravy", weight: 90, ingredientList: ["country sausage", "peppered white gravy", "biscuit dough"] },
      { name: "Meat lovers hash", weight: 90, ingredientList: ["bacon", "sausage", "ham", "potatoes", "cheddar cheese"] },
      { name: "Maple sausage potato hash", weight: 70, ingredientList: ["maple-glazed sausage", "diced potatoes", "scrambled eggs"] },
      { name: "Homestead", weight: 70, ingredientList: ["ham", "cheddar", "sautéed onions", "scrambled eggs"] },
      { name: "Western sunrise scramble", weight: 60, ingredientList: ["bell peppers", "onions", "ham", "scrambled eggs", "pepper jack cheese"] },
      { name: "Chicken & waffles", weight: 50, ingredientList: ["crispy chicken", "scrambled eggs", "maple butter sauce"] },
      { name: "Chorizo breakfast taco", weight: 90, ingredientList: ["chorizo", "scrambled eggs", "cheddar cheese", "pico de gallo"] },
      { name: "Country fried steak & egg", weight: 80, ingredientList: ["country fried beef", "scrambled eggs", "white gravy"] },
      { name: "Smoked salmon", weight: 30, ingredientList: ["smoked salmon", "egg whites", "cream cheese", "chives"] },
      { name: "Canadian lumberjack", weight: 50, ingredientList: ["peameal bacon", "cheddar", "hash browns", "maple syrup glaze"] },
      { name: "Avocado toast", weight: 60, ingredientList: ["mashed avocado", "feta cheese", "diced tomatoes", "scrambled eggs"] },
      { name: "Breakfast burrito", weight: 90, ingredientList: ["sausage", "black beans", "scrambled eggs", "pepper jack cheese", "salsa verde"] },
      { name: "Southwest huevos rancheros", weight: 50, ingredientList: ["black beans", "scrambled eggs", "roasted peppers", "queso fresco", "chipotle sauce"] },
      { name: "Korean breakfast bowl", weight: 30, ingredientList: ["bulgogi beef", "kimchi", "egg", "white rice"] },
      { name: "Mediterranean morning", weight: 20, ingredientList: ["spinach", "feta cheese", "sun-dried tomato", "scrambled eggs"] },
      { name: "Everything bagel", weight: 20, ingredientList: ["egg", "ham", "cheddar cheese", "everything bagel seasoning crust"] },
      { name: "Denver omelet", weight: 40, ingredientList: ["ham", "green bell peppers", "onions", "cheddar cheese", "eggs"] },
      { name: "Sausage & sweet potato hash", weight: 20, ingredientList: ["pork sausage", "roasted sweet potatoes", "scrambled eggs"] },
    ],
    modifier: [
      { name: "None", weight: 100 },
      { name: "Cream cheese", weight: 50 },
      { name: "Chives", weight: 40 },
      { name: "Shredded cheddar", weight: 50 },
      { name: "Avocado slices", weight: 20 },
      { name: "Cilantro", weight: 20 },
      { name: "Maple syrup drizzle", weight: 20 },
      { name: "Goat cheese crumbles", weight: 30 },
      { name: "Pepper jack", weight: 40 },
      { name: "Shredded baby spinach", weight: 20 },
      { name: "Garlic aioli", weight: 10 },
      { name: "Cholula", weight: 20 },
      { name: "Tabasco", weight: 30 },
      { name: "Pickled red onion", weight: 20 },
      { name: "Crumbled breakfast sausage", weight: 40 },
      { name: "Diced bell peppers", weight: 30 },
      { name: "Hashbrown crumbles", weight: 40 },
      { name: "Yukon gold potato cubes", weight: 30 },
      { name: "Hickory ham cubes", weight: 30 },
      { name: "Sriracha", weight: 20 },
      { name: "Crispy tortilla strips", weight: 10 },
    ],
    crust: [
      { name: "Original", weight: 100 },
      { name: "Croissant", weight: 30 },
      { name: "Pretzel", weight: 20 },
      { name: "Extra crispy", weight: 30 },
      { name: "Buttery biscuit", weight: 20 },
      { name: "Fried waffle", weight: 10 },
      { name: "Flakey puff pastry", weight: 20 },
      { name: "Sourdough", weight: 5 },
    ],
    seasoning: [
      { name: "None", weight: 100 },
      { name: "Cracked black pepper", weight: 30 },
      { name: "Crushed red pepper", weight: 30 },
      { name: "Ranch", weight: 20 },
      { name: "Hot honey", weight: 20 },
      { name: "Garlic onion", weight: 20 },
      { name: "Everything bagel", weight: 10 },
      { name: "Smoked paprika", weight: 10 },
      { name: "Smoky maple dust", weight: 10 },
      { name: "Sea salt", weight: 20 },
      { name: "Brown sugar", weight: 20 },
      { name: "Sweet chili glaze", weight: 20 },
      { name: "Herbed parmesan", weight: 10 },
      { name: "Sage & thyme blend", weight: 10 },
      { name: "Cinnamon", weight: 20 },
      { name: "Buttery herbs", weight: 30 },
      { name: "Habanero spice", weight: 10 },
    ],
  },
  dinner: {
    base: [
      { name: "Pepperoni pizza", weight: 100, ingredientList: ["pepperoni", "mozzarella"] },
      { name: "Meat lovers pizza", weight: 100, ingredientList: ["pepperoni", "sausage", "ham", "mozzarella"] },
      { name: "Four cheese pizza", weight: 100, ingredientList: ["mozzarella", "provolone", "parmesan", "romano"] },
      { name: "Five cheese pizza", weight: 30, ingredientList: ["mozzarella", "cheddar", "asiago", "provolone", "parmesan"] },
      { name: "Meatballs & mozzarella", weight: 60, ingredientList: ["Italian-style meatballs", "marinara sauce", "mozzarella"] },
      { name: "Philly steak & cheese", weight: 70, ingredientList: ["sliced steak", "sautéed onions", "bell peppers", "provolone"] },
      { name: "Steak & cheddar", weight: 70, ingredientList: ["grilled steak", "sharp cheddar cheese"] },
      { name: "Ham & cheese", weight: 80, ingredientList: ["honey ham", "Swiss cheese"] },
      { name: "Chicken bacon ranch", weight: 50, ingredientList: ["grilled chicken", "smoked bacon", "ranch sauce", "mozzarella"] },
      { name: "Jalapeño steak with cheese", weight: 20, ingredientList: ["spicy steak", "jalapeños", "pepper jack cheese"] },
      { name: "Cheeseburger", weight: 50, ingredientList: ["ground beef", "cheddar cheese", "ketchup-mustard sauce"] },
      { name: "Turkey, bacon & cheese", weight: 60, ingredientList: ["roasted turkey", "bacon", "American cheese"] },
      { name: "Chicken, mushroom & spinach", weight: 30, ingredientList: ["grilled chicken", "mushrooms", "spinach", "Swiss cheese"] },
      { name: "Chicken, broccoli & cheddar", weight: 60, ingredientList: ["diced chicken", "broccoli florets", "cheddar cheese"] },
      { name: "Chicken parmesan", weight: 80, ingredientList: ["breaded chicken", "marinara sauce", "mozzarella", "parmesan"] },
      { name: "BBQ beef", weight: 60, ingredientList: ["shredded beef", "barbecue sauce", "cheddar cheese"] },
      { name: "Beef Taco", weight: 40, ingredientList: ["seasoned ground beef", "cheddar cheese", "black beans"] },
      { name: "Steak Fajita", weight: 30, ingredientList: ["fajita steak strips", "grilled peppers", "onions", "Monterey Jack cheese"] },
      { name: "Italian sub", weight: 20, ingredientList: ["salami", "pepperoni", "ham", "provolone", "banana peppers"] },
      { name: "Veggie delight", weight: 20, ingredientList: ["zucchini", "bell peppers", "spinach", "mozzarella", "red onion"] },
    ],
    modifier: [
      { name: "None", weight: 100 },
      { name: "Caramelized onions", weight: 30 },
      { name: "Crumbled bacon", weight: 30 },
      { name: "Roasted red peppers", weight: 20 },
      { name: "Guacamole", weight: 10 },
      { name: "Shaved parmesan", weight: 20 },
      { name: "Pepperoncini rings", weight: 20 },
      { name: "Crispy onion straws", weight: 20 },
      { name: "Shredded baby spinach", weight: 10 },
      { name: "Dill pickle slices", weight: 10 },
      { name: "Crispy tortilla strips", weight: 30 },
      { name: "Fresh basil", weight: 20 },
      { name: "Fire-roasted corn", weight: 20 },
      { name: "Jalapeños", weight: 30 },
      { name: "Chopped green olives", weight: 10 },
      { name: "Crumbled blue cheese", weight: 10 },
      { name: "Pepperoni crumbles", weight: 30 },
      { name: "Corn relish", weight: 10 },
      { name: "Banana peppers", weight: 20 },
      { name: "Sweet BBQ sauce", weight: 10 },
      { name: "Artichoke hearts", weight: 10 },
    ],
    crust: [
      { name: "Original", weight: 100 },
      { name: "Croissant", weight: 30 },
      { name: "Pretzel", weight: 20 },
      { name: "Extra crispy", weight: 30 },
      { name: "Buttery biscuit", weight: 20 },
      { name: "Fried waffle", weight: 10 },
      { name: "Flakey puff pastry", weight: 20 },
      { name: "Sourdough", weight: 5 },
    ],
    seasoning: [
      { name: "None", weight: 100 },
      { name: "Garlic butter parmesan", weight: 20 },
      { name: "Italian herb", weight: 30 },
      { name: "Cracked black pepper", weight: 30 },
      { name: "Spicy taco dust", weight: 20 },
      { name: "Ranch", weight: 25 },
      { name: "Extra zesty ranch", weight: 10 },
      { name: "Hot honey", weight: 20 },
      { name: "Crushed red pepper", weight: 30 },
      { name: "Garlic onion", weight: 10 },
      { name: "Smoked paprika", weight: 10 },
      { name: "Sweet chili glaze", weight: 10 },
      { name: "Buttery herbs", weight: 20 },
      { name: "Truffle salt & thyme", weight: 20 },
      { name: "Sea salt", weight: 20 },
      { name: "Habanero spice", weight: 15 },
      { name: "Ghost pepper spice", weight: 10 },
    ],
  },
  dessert: {
    base: [
      { name: "Double fudge brownie", weight: 100, ingredientList: ["fudge brownie filling", "chocolate chips"] },
      { name: "S’mores", weight: 100, ingredientList: ["chocolate", "marshmallow cream", "graham cracker crumbles"] },
      { name: "Chocolate lava cake", weight: 60, ingredientList: ["molten chocolate center", "dark chocolate cake"] },
      { name: "Nutella & banana crumble", weight: 80, ingredientList: ["hazelnut spread", "banana slices", "oat crumble"] },
      { name: "Peanut butter cup explosion", weight: 100, ingredientList: ["peanut butter", "milk chocolate"] },
      { name: "Cookies & cream dream", weight: 60, ingredientList: ["vanilla cream", "chocolate cookie pieces"] },
      { name: "Turtle sundae", weight: 50, ingredientList: ["caramel", "pecans", "chocolate chunks"] },
      { name: "Mexican chocolate", weight: 20, ingredientList: ["spiced dark chocolate", "cinnamon"] },
      { name: "Strawberry cheesecake", weight: 40, ingredientList: ["strawberry filling", "cheesecake cream"] },
      { name: "Peach cobbler", weight: 30, ingredientList: ["spiced peach filling", "streusel topping"] },
      { name: "Apple pie", weight: 50, ingredientList: ["baked apple filling", "cinnamon sugar"] },
      { name: "Cinnamon roll delight", weight: 60, ingredientList: ["cinnamon brown sugar", "cream cheese icing"] },
      { name: "Birthday cake", weight: 40, ingredientList: ["funfetti cake batter", "vanilla frosting"] },
      { name: "Churro crunch", weight: 50, ingredientList: ["cinnamon sugar filling", "crunchy pastry bits"] },
      { name: "Boston cream", weight: 40, ingredientList: ["custard filling", "chocolate ganache"] },
      { name: "Lemon meringue", weight: 20, ingredientList: ["lemon curd", "marshmallow fluff"] },
      { name: "Tiramisu twist", weight: 20, ingredientList: ["espresso cream", "mascarpone filling"] },
      { name: "Red velvet cheesecake", weight: 40, ingredientList: ["red velvet cake", "cream cheese swirl"] },
      { name: "Gingerbread house", weight: 40, ingredientList: ["ginger-molasses filling", "vanilla icing"] },
      { name: "Cookie dough", weight: 70, ingredientList: ["chocolate chip cookie dough", "fudge swirl"] },
    ],
    modifier: [
      { name: "None", weight: 100 },
      { name: "Whipped cream", weight: 20 },
      { name: "Cream cheese", weight: 30 },
      { name: "Marshmallow fluff", weight: 30 },
      { name: "Salted caramel sauce", weight: 20 },
      { name: "Peanut butter drizzle", weight: 30 },
      { name: "Hot fudge", weight: 40 },
      { name: "Custard", weight: 20 },
      { name: "Espresso whipped cream", weight: 20 },
      { name: "Chocolate chips", weight: 40 },
      { name: "Toffee bits", weight: 30 },
      { name: "Gingersnap crumbles", weight: 20 },
      { name: "Chopped pecans", weight: 30 },
      { name: "Nutella swirl", weight: 30 },
      { name: "Pistachio crumbles", weight: 10 },
      { name: "Macadamia nuts", weight: 10 },
      { name: "Cheesecake", weight: 10 },
      { name: "Coconut", weight: 20 },
      { name: "Streusel crumble", weight: 20 },
      { name: "Sliced bananas", weight: 10 },
      { name: "Fresh strawberries", weight: 10 },
    ],
    crust: [
      { name: "Original", weight: 100 },
      { name: "Croissant", weight: 30 },
      { name: "Pretzel", weight: 20 },
      { name: "Extra crispy", weight: 30 },
      { name: "Buttery biscuit", weight: 20 },
      { name: "Fried waffle", weight: 10 },
      { name: "Flakey puff pastry", weight: 20 },
      { name: "Sourdough", weight: 5 },
    ],
    seasoning: [
      { name: "None", weight: 100 },
      { name: "Cinnamon sugar dust", weight: 20 },
      { name: "Powdered sugar glaze", weight: 20 },
      { name: "Salted Caramel sugar", weight: 20 },
      { name: "Brown sugar dust", weight: 20 },
      { name: "Toasted coconut flakes", weight: 10 },
      { name: "Marshmallow glaze", weight: 10 },
      { name: "Maple sugar glaze", weight: 20 },
      { name: "Honey butter glaze", weight: 10 },
      { name: "Sprinkles", weight: 10 },
      { name: "Chocolate sprinkles", weight: 20 },
      { name: "Oreo crumble dust", weight: 30 },
      { name: "Cocoa sugar", weight: 30 },
      { name: "Espresso sugar dust", weight: 10 },
      { name: "Cinnamon chili cocoa dust", weight: 10 },
      { name: "Lemon zest sugar", weight: 10 },
      { name: "Glazed donut", weight: 10 },
    ],
  },
};

export default hotPocketData; 